### ISSUE TITLE
Failed to attach: unable to communicate with remote frida-server; 

### ISSUE THREAD

**Issue by LovingGt** [dpnishant/appmon#48] opened 2017-08-31 14:19 UTC
When i try "frida -U -p 0" 
Failed to attach: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
Iphone 4.s
ios 9.3.5
Frida 10.5.8 (client)
frida 32bit "10.5.8 ( server ) 

(lldb) command source -s 0 '/tmp/A2FA8077-26DB-4AE5-B4F2-44FB956D8A81/fruitstrap-lldb-prep-cmds-a6173add9ee6f9a554b5de7c6098ad2dc2a54ad7'
Executing commands in '/tmp/A2FA8077-26DB-4AE5-B4F2-44FB956D8A81/fruitstrap-lldb-prep-cmds-a6173add9ee6f9a554b5de7c6098ad2dc2a54ad7'.
(lldb)     platform select remote-ios --sysroot '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/9.3 (13E230)/Symbols'
  Platform: remote-ios
 Connected: no
  SDK Path: "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/9.3 (13E230)/Symbols"
(lldb)     target create "/Users/PhidiaS-MAC/Downloads/appmon-master/ipa_installer/apps/Instagramex-injected-resigned/Payload/Instagram.app"
Current executable set to '/Users/PhidiaS-MAC/Downloads/appmon-master/ipa_installer/apps/Instagramex-injected-resigned/Payload/Instagram.app' (armv7).
(lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/08262CEB-19D2-442B-99CB-181E707E5923/Instagram.app"
(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:49440"
(lldb)     command script import "/tmp/A2FA8077-26DB-4AE5-B4F2-44FB956D8A81/fruitstrap_a6173add9ee6f9a554b5de7c6098ad2dc2a54ad7.py"
(lldb)     command script add -f fruitstrap_a6173add9ee6f9a554b5de7c6098ad2dc2a54ad7.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_a6173add9ee6f9a554b5de7c6098ad2dc2a54ad7.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_a6173add9ee6f9a554b5de7c6098ad2dc2a54ad7.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_a6173add9ee6f9a554b5de7c6098ad2dc2a54ad7.safequit_command safequit
(lldb)     connect
(lldb)     run
success
2017-08-31 17:13:10.648 Instagram[531:16186] Frida: Listening on TCP port 27042

**Comment by dpnishant** [comment] 2017-10-09 18:57
@LovingGt This is a known issue on Android. Probably @oleavr can answer the reason. But I guess, attaching a regular app name it should work. Can you please confirm?

**Comment by dpnishant** [comment] 2017-11-16 18:26
Can't reproduce this issue on my side. Hence closing

**Closed by dpnishant** 2017-11-16 18:26 UTC
